### ISSUE TITLE
画像差し替えした際に、元の画像のサイズがそのまま残っている

### ISSUE THREAD

**Issue by kageori** [yugeta/image-motion#12]
https://user-images.githubusercontent.com/31335394/182163463-819ee0d4-f04b-4787-8a9b-9f4c9c59b2a8.mp4

**Comment by yugeta** [comment]
これ、shapeなどのデータが引き継げなくなるので、サイズを継続する仕様にしているんだけど、プロパティにリセットボタンをつけて、手動で操作するようにしようと思うんだけど、それでもいいかな？
それとも、同じサイズかどうかを判定して、違っている場合は、アニメーションやcenter値がリセットされるconfirmを提示する方が親切かとも思いました。
とりあえず、両面対応したいと思います。
今しばらくお待ちを

**Comment by kageori** [comment]
なるほど、そう考えるとこのまま維持してcloseでも良さそうな気がしてきました。
今も手入力でサイズ写せば、あまり問題なさそうなので。

**Comment by yugeta** [comment]
とりあえず、自動化処理を入れたいので、ちょっとだけお待ちを！

**Comment by yugeta** [comment]
修正完了しました。
同じサイズの画像はそのまま入れ替えをして、サイズが違う画像は、shape情報をリセットして入れ替えするようにしました。
