### ISSUE TITLE
細かいパーツのshapeを触りたい時にどうするか

### ISSUE THREAD

**Issue by kageori** [yugeta/image-motion#13]
あまりに細かいパーツ（例: 口）だと、変形の頂点に隠れてしまう。
拡大した時に、頂点サイズを一緒に拡大しないようにすることは可能？

<img width="1100" alt="スクリーンショット 2022-08-01 16 00 29" src="https://user-images.githubusercontent.com/31335394/182165198-84cb3e09-c1f3-4f3d-ba1c-e854a1afb0cc.png">

**Comment by yugeta** [comment]
ポイントの大きさをscaleによって小さくするようにセットしてみました。
（センターポイントと同じ大きさになってます）
