### ISSUE TITLE
画像差し替え後のパーツのshapeを変形させると、エラーが出る

### ISSUE THREAD

**Issue by kageori** [yugeta/image-motion#14]
口のパーツを、周囲の透明部分を削除したものに置き換えて変形したところ、エラーが出た
（差し替え前の透明部分のあるものでshape変更してみたところ、問題なかった）

https://user-images.githubusercontent.com/31335394/182167723-9c0f31d2-28f1-43ca-8e0e-f6dcc45eba68.mp4

<img width="486" alt="スクリーンショット 2022-08-01 16 08 49" src="https://user-images.githubusercontent.com/31335394/182168263-fd7b9b79-1c37-4de2-b53e-5b0fcda5dec4.png">

**Comment by yugeta** [comment]
画像差し替えでのshapeの扱いを修正しているので、最新バージョンでエラーが出るようなら再確認します。

**Comment by kageori** [comment]
しばらく様子見ていて大丈夫そうだったので、closeします。
