### ISSUE TITLE
durationが保存されない

### ISSUE THREAD

**Issue by kageori** [yugeta/image-motion#16]
アニメーションのdurationに1以外をセットしてsave後、loadすると1に戻っている

**Comment by yugeta** [comment]
修正完了！
アニメーションの設定値を保持できるようになりました。
あと、気が付かないうちに初期値ではない設定が適用されるのを防ぐために、アニメーション切替時に一旦リセットする処理も追加したので、新規作成は常にデフォルト値を参照するようにしました。

**Comment by kageori** [comment]
duration保存されていることを確認しました！
