### ISSUE TITLE
アニメーションのコピー

### ISSUE THREAD

**Issue by kageori** [yugeta/image-motion#17]
作成したアニメーションをコピーできるととてもありがたい（それをベースに新しいアニメーションを作りたい）

**Comment by yugeta** [comment]
仕様1. 別のjsonファイルのアニメーション情報のみを読み込む（画像データが同じ状態であること）
仕様2. 同じタイムライン上でコピーする（shapeはコピーできないと同じ情報を複製するのが難しい）

**Comment by yugeta** [comment]
仕様2の機能追加完了。

**Comment by yugeta** [comment]
Request : アニメーション名を変更できるように

**Comment by yugeta** [comment]
アニメーション設定のヘッダ部分を大幅に変更しました。
これまでのように、自由に記入してリスト追加すると、編集などの作業が煩雑になるので、
```
add : 新規登録
edit : 既存の編集
delete : 削除
copy : 現在選択中のアニメーを別名称にコピー
```
このように機能を分けてアイコンを設置しました。
コピーもできるようなったし、今後機能追加をしやすくなったと思います。
