### ISSUE TITLE
アップロード画面の階層の折りたたみ

### ISSUE THREAD

**Issue by kageori** [yugeta/image-motion#19]
アップロード画面の階層の折りたたみができると嬉しい。

<img width="266" alt="スクリーンショット 2022-08-02 1 56 32" src="https://user-images.githubusercontent.com/31335394/182264183-bb7239a8-8555-49e0-95a2-4931afa5755d.png">

**Comment by yugeta** [comment]
階層を折り畳める機能を追加しました。
画像横の「+」「-」をクリックすると、開閉します。
+ : 閉じた状態 
- : 開いた状態

<img width="268" alt="スクリーンショット 2022-08-03 17 02 50" src="https://user-images.githubusercontent.com/2545771/182556543-b086c7f4-0e3f-4b67-b2ac-1056f1174848.png">
