### ISSUE TITLE
キーフレームの値を削除できないことがある

### ISSUE THREAD

**Issue by kageori** [yugeta/image-motion#2]
- 生成したキーをずらした場合に起こることがある？

**Comment by yugeta** [comment]
https://user-images.githubusercontent.com/2545771/182023934-1379f735-eda5-43bd-851d-9d91a280d375.mp4

再現しないな〜、何の条件があるんだろうか？

引き続き追ってみます。

**Comment by kageori** [comment]
再現しました。
やはり、生成後にずらすのが良くなさそうです。

https://user-images.githubusercontent.com/31335394/182026619-bf5ee478-df6d-4e8b-a5d2-11becc477f51.mp4

**Comment by yugeta** [comment]
うう、こちらで再現できず・・・
同じ場所に複数のkeyが追加されている感じなのかな？

**Comment by kageori** [comment]
これ、もしかしたらjsonが壊れていた説があるんじゃないかと思いました。

しばらく見守りますが、何もなさそうならcloseでも良いかなと思いました。
