### ISSUE TITLE
キーフレームに設定していない回転が起こってしまう

### ISSUE THREAD

**Issue by kageori** [yugeta/image-motion#27]
0%に0、20%, 40%のところに-3のRotaionを設定したが、21~39%の間で設定していないはずの-30傾く。

https://user-images.githubusercontent.com/31335394/182884368-afa532c0-6c98-4943-a5b0-d09fb351694f.mp4

**Comment by kageori** [comment]
作業途中何処かでjsonが壊れた可能性があります（↑これを再度開こうとして開けなくなっていたので）。
一応別途データ送付します。

**Comment by yugeta** [comment]
影織ちゃんから送ってもらった壊れたデータを解析してみて気がついたポイント

1. 134行目の値がブランクになっているのが謎・・・
```
"shape_table": {},
"parent": "328A773C-8CE2-4CB0-AA1A-83613E661C91",
"hidden": 0,
"shape_use": 1
```
shape_use=1の場合は、table値をx,yでセットしなければいけないのだが、ブランクは以前のバグが残っているのか？それとも何かの操作でこうなってしまう事があるのか？
引き続き調査する。

2. 664行目のshape.pointsとshape.matrixの内容がブランク配列になっている。
```
       "0C08E413-9FBB-4694-AFC1-7EB0A1719652": {
          "keyframes": {
            "0": {
              "shape": {
                "points": [],
                "matrix": []
              }
            }
          }
        }
      }
```
このオブジェクトのshape_useが1ではないので、shapeを解除した段階で、keyframeデータを消し去る処理を確実にしないといけないという事が分かった。

**Comment by yugeta** [comment]
アニメーションがカクカクするのは、値が何故か数値型ではなく、文字型で保存されてた！
型判定が定まっていない処理が潜んでいるらしい、見直そう！

**Comment by yugeta** [comment]
range設定をすると文字列で保持されてしまう事が判明！

**Comment by yugeta** [comment]
基本的にデータを修正するので壊れたファイルがあれば、送ってください。

**Comment by kageori** [comment]
今のところ、壊れたのはお送りした分だけです！
