### ISSUE TITLE
shapeの四隅の点が動かないことがある

### ISSUE THREAD

**Issue by kageori** [yugeta/image-motion#28]
https://user-images.githubusercontent.com/31335394/182894769-c9c30c8a-6d28-4e77-8913-9e6846ce7ce9.mp4

移動させた後resetすると、頂点が思わぬところにずれた
<img width="282" alt="スクリーンショット 2022-08-04 18 03 49" src="https://user-images.githubusercontent.com/31335394/182894774-2cbfc76b-f7da-479c-9ad0-6542a4fc5ec2.png">

**Comment by yugeta** [comment]
shape周りの処理が、煩雑化していたので、できる限りのリファクタリングをしてみました。
その際に、不都合な処理を見つけたので修正しておきました。
※他にもバグがあるかもしれないので、本件まだcloseしないでおきましょう。

**Comment by kageori** [comment]
最新masterで、頂点動かないようです。


https://user-images.githubusercontent.com/31335394/183290882-0b5bb151-9c2e-4a0b-9633-0c4e301910c3.mp4

**Comment by kageori** [comment]
一旦フォーカスを外して（触っていたものと別のパーツを選択して）再選択すると反映されるようです。

**Comment by yugeta** [comment]
リファクタリングした際に、インスタンス構築で処理が足りていない箇所がありました！
漏れバグ失礼しました！！！
