### ISSUE TITLE
ロードしたら、前に表示していたものは一旦消す

### ISSUE THREAD

**Issue by kageori** [yugeta/image-motion#29]
現状は、どんどん追加されてしまうが、消した方がいい？（複数のアニメーションを開いて設定することはおそらくないので）

<img width="1103" alt="スクリーンショット 2022-08-04 18 24 49" src="https://user-images.githubusercontent.com/31335394/182902399-d5f14169-a671-4bb5-84ff-29ebe2410aa4.png">

**Comment by yugeta** [comment]
loadしたら基本的に消すようにします。
あと、新規モードとして、画面クリアするのも用意します。（フォトショップの新規みたいに「new」かな）

**Comment by yugeta** [comment]
Fileメニューに「New」を追加したのと、
Load -> Openに変更しました。
作業をしている状態で、Openをした場合、一旦Newしてからデータをロードする仕様にしました。
