### ISSUE TITLE
画像位置調整

### ISSUE THREAD

**Issue by kageori** [yugeta/image-motion#3]
- 未トリミング画像を入れると、左端がぎりぎりになり、Shape変更時に枠外に出てしまうことがある（添付動画参照）
https://user-images.githubusercontent.com/31335394/182004441-7fb89a54-a3b4-46c6-93b2-657c480dd34a.mov

**Comment by yugeta** [comment]
影織ちゃん撮影動画

https://user-images.githubusercontent.com/2545771/182023987-380dd0e0-a14b-4a0c-af69-0873b450a66f.mp4

**Comment by yugeta** [comment]
影織ちゃん撮影撮影動画

https://user-images.githubusercontent.com/2545771/182024023-0acce072-81c7-4f51-993a-3adbcc19cfc2.mp4

**Comment by yugeta** [comment]
画面を動かせる機能を追加しました。
お試しあれ！

<img width="594" alt="スクリーンショット 2022-08-01 7 14 59" src="https://user-images.githubusercontent.com/2545771/182047467-a079e7b1-6100-4ae5-9747-be82389d2fab.png">
