### ISSUE TITLE
Shapeアニメーションのキーフレームを追加できない

### ISSUE THREAD

**Issue by kageori** [yugeta/image-motion#41]
positionやscaleなどの他の部分は追加できる

https://user-images.githubusercontent.com/31335394/184496332-f0cfd400-3a8e-44eb-a03a-dd909588ec59.mp4

**Comment by yugeta** [comment]
@kageori shapeが未使用になっているので、キーフレームが追加できないです。ONにすると追加できるはず！

**Comment by kageori** [comment]
なるほど、解決しました！お騒がせしました。
