### ISSUE TITLE
upload画面のtransform表示のずれ

### ISSUE THREAD

**Issue by kageori** [yugeta/image-motion#42]
パーツにフォーカスをあてて編集する際、数値と表示にずれが出てしまう。

https://user-images.githubusercontent.com/31335394/184497094-fb493a42-1fb3-4b09-b40a-35e9ee384ed4.mp4

**Comment by yugeta** [comment]
これ、jsonデータ送ってください。ちょっと確認したいパラメータがあるので。
（お手すきの時にでも）

**Comment by yugeta** [comment]
animationモードで、animation-name（登録されているアニメーション）が選択されている状態で、uploadのモードに移動して、imageに選択をすると、animationのキーフレーム情報がくっついてきてしまうので、
モードを切り替えるときには、animation-nameを解除するように仕様を変更します。

**Comment by yugeta** [comment]
更新までの間は、選択されたanimationをブランク状態にしてからモード移動すると、正常に動くはずなので、お手数ですが、そちらで対応してください。
