### ISSUE TITLE
アニメーションのpositionの入力値と表示のずれ

### ISSUE THREAD

**Issue by kageori** [yugeta/image-motion#44]
scaleがついたことで計算結果が変わっている？

https://user-images.githubusercontent.com/31335394/184500253-82229258-4479-4cfa-929f-0931cca39364.mp4

**Comment by yugeta** [comment]
scaleの値でpositionの値が変わりますね。
これを回避するには、今のところは、paperの上階層に移動用のダミーオブジェクトを置いて、その子にpaperをセットして、scaleはpaper、position（移動）は親のダミー画像（小さめサイズ）で透明画像でコントロールすればできると思います。
すこし複雑になるかもしれませんが、単一オブジェクトで扱えるような仕様がないか検討してみます。
もしかしたらフォルダ機能を付けると、ダミーオブジェクトなどセットせずにセットできるようになるかな〜とか考えてます。
