### ISSUE TITLE
キーフレームを打たずにopacityを変更すると、他のopacityに影響が出る？

### ISSUE THREAD

**Issue by kageori** [yugeta/image-motion#45]
キーフレームを打ち直したら（紙が出てくるアニメーションは1、それ以外は0）正しく表示されました。

https://user-images.githubusercontent.com/31335394/184500821-cbf18493-9df5-45f4-af4c-3e45a3078692.mp4

**Comment by yugeta** [comment]
アニメーション切り替えの際に、アニメーションのプレビューをリセットする処理でopacityがセットされていないと思われるので、修正します。
