### ISSUE TITLE
180度以上のrotateの実現

### ISSUE THREAD

**Issue by kageori** [yugeta/image-motion#49]
180度以上回転させたい場合、180度まで移動させたキーフレームを、1％後に-180度に移すと、playerで再生した際に、その間を補完するので、残像が生まれてしまう。
rotateのレンジが広がって、スムーズな回転ができると嬉しい。

https://user-images.githubusercontent.com/31335394/185253288-9d989bc0-cd61-43c6-8676-c5d9509f3ec0.mp4

**Comment by yugeta** [comment]
表示の拡大率やposition,rotate,scaleなど、rangeを利用しているため、上限と下限の値をセットしているため、もう少し柔軟に使えるようにするために、数値入力して上限、下限を超えた場合に、rangeのmin,maxの値をそれに合わせて変更するような仕様にしたいと思います。

これにより、実質、上限、下限の制約は無くなります。
rangeによる操作の利便性を残すために、データ読込時にrangeのmin,max値を取得する関数などを作って、現在のデータもそのままで対応できるような仕様にする予定です。

**Comment by yugeta** [comment]
action（アニメーション設定）のrangeと画像表示のscaleのrange箇所を入力値がrange-limitを超えた場合に、それを最大値にするように自動セットするようにしました。
再読み込みをした場合（パーツを選択し直した場合）などでも自動で対応できるようにしました。
