### ISSUE TITLE
画像をドラッグしようとするとフォーカスが外れてしまう

### ISSUE THREAD

**Issue by kageori** [yugeta/image-motion#5]
画像をドラッグしようとした時に、別レイヤーの透明部分の方にフォーカスが当たってしまう（重なり順の問題？）

https://user-images.githubusercontent.com/31335394/182025490-635f3d9b-0d7d-46aa-9eef-40bc1b676c0b.mp4

**Comment by kageori** [comment]
一旦、上に重なっているレイヤー（この場合はbodyに対するleg）を非表示にすることで移動可能になった

**Comment by yugeta** [comment]
パーツの前後判定がうまく出来ていない箇所があるかも。
画像を全部同じサイズにしたので、より前後関係がしっかりと機能しないといけないんですね。
その他のパーツを隠すと選択できると思うので、しばらくはその操作でお願いします。
