### ISSUE TITLE
中心点の最小値設定

### ISSUE THREAD

**Issue by kageori** [yugeta/image-motion#51]
引きで見た時に、回転の中心点がかなり小さくなって、操作が難しくなるので、ある一定以下のサイズにならないようになると嬉しい。

階層の目のマークくらいのサイズくらいだとちょうどいいかもしれない。

<img width="366" alt="スクリーンショット 2022-08-25 22 44 42" src="https://user-images.githubusercontent.com/31335394/186765758-de152e82-c8d3-4352-910b-c591f8a46aab.png">

**Comment by yugeta** [comment]
センターサイズを拡大率で一定の大きさになる（見た目が20px , 20pxのサイズになる）ような仕様に設定。
サイズの変更は今の所システムoptionの値で設定するので、ユーザーが変更は不可。
