### ISSUE TITLE
PlayモードでのShapeアニメーションのduration不具合

### ISSUE THREAD

**Issue by kageori** [yugeta/image-motion#54]
おそらくPlayモード側で、ShapeアニメーションのみDurationが反映されていない。

下記の例では、左手の指の曲げ伸ばしが、4秒間で一巡のアニメーションの中で、4回再生されてしまっている（想定では1回になってほしい）。

https://user-images.githubusercontent.com/31335394/187082467-8ccbdf30-8fe6-48df-92ec-07e7efcc6d35.mp4

**Comment by yugeta** [comment]
sound機能を入れたタイミングでdurationが正常に取得できていないバグがありました。
見つけてもらって感謝！
ついでに、sound機能のrepeat機能のバグも見つかったので、同時に修正済み

**Comment by yugeta** [comment]
playerはiframe表示しているので、iframeのキャッシュがしつこく残る傾向があるので、iframeのブラウザキャッシュ回避処理を追加対応します。

**Comment by yugeta** [comment]
とりあえず、iframeキャッシュ回避処理追加しました。
