### ISSUE TITLE
Playモードで音声再生が最初一回のみになっている

### ISSUE THREAD

**Issue by kageori** [yugeta/image-motion#57]
Playモードで見ると、音声再生が最初の一回のみになっているが、アニメーションが繰り返すのに合わせて、繰り返し再生されるといいかもしれない？

**Comment by yugeta** [comment]
Playモードの音声再生が正常に機能していなかったので、動作するようにしました。
※見つけられていない不具合があるかも・・・

**Comment by kageori** [comment]
ありがとうございます！

こちら、
- 別のモード（アニメーションやアップロード）に切り替えても音が鳴り続ける（もう一度Playモードに戻ると止まる）
- 添付のように0%のところにSoundを設定してしまうと、Playモードで音が鳴らなくなる（1%以降に設定すれば鳴ります）
<img width="419" alt="スクリーンショット 2022-09-10 18 09 21" src="https://user-images.githubusercontent.com/31335394/189491970-c6a4d1c7-a48f-4f29-93bd-4d2d8f53e12c.png">


という別の現象を発見しました。お手隙の際に見ていただけるとありがたいです...！

**Comment by yugeta** [comment]
playを押した時にkeyframe++となっていたので、インクリメントの場所を変更しました。
こんなニッチなバグ見つけてくれて感謝！

**Comment by yugeta** [comment]
ついでにもう一つ見つけたんだけど、アニメーションを再生する時に、何かパーツが選択されていないと音がならないんだけど、これはやっぱりなったほうがいいよね？
そして、画面右側のpeoperty欄に、選択していないsoundの情報がでているので、やはりバグ扱いにします。

**Comment by yugeta** [comment]
以下２点を修正しました。
・property表示を、選択しているアイテムのみにする
・アニメーションプレビュー時に、サウンドの再生を確実に行う。

**Comment by kageori** [comment]
ありがとうございます！大変助かります！！

- 別のモード（アニメーションやアップロード）に切り替えても音が鳴り続ける（もう一度Playモードに戻ると止まる）
-> こちら、まだ鳴り続けているようです。

- 0%のところにSoundを設定してしまうと、Playモードで音が鳴らなくなる（1%以降に設定すれば鳴ります）
-> こちら、0%だとやはり音が聞こえないようです...

いずれも検証環境は、最新ブランチでスーパーリロード済です。

**Comment by yugeta** [comment]
ヘッダ機能を切り替えてもiframeの裏で音がなり続けている

**Comment by yugeta** [comment]
0フレーム音声の再生改修しました。

**Comment by yugeta** [comment]
ヘッダ機能の切替時にiframe内をリセットする仕様を追加して、音を継続しないようにしました。
