### ISSUE TITLE
Player : Netlifyで読み込んだ時に表示サイズが小さくなる。

### ISSUE THREAD

**Issue by yugeta** [yugeta/image-motion#59]
![303081406_479190797397607_7766383675366900777_n](https://user-images.githubusercontent.com/2545771/188288329-b9dceec5-6b65-4c70-b96c-b5581341afb9.png)

playerの仕様で、表示させるelementに読み込んだ画像のnaturalWidth(height)のサイズ比率で自動的に表示サイズをfitさせる初期処理があるが、
読み込みが遅い場合にこの比率が正確にならない可能性がある。
（調査前の所感）

とにかくこれは修正しないと、ゲームで遊ぶ時に、回線速度環境にとって、正常にキャラクタが表示されない可能性が高いので、重要！

**Comment by yugeta** [comment]
うう、再現ができない・・・
もしかすると、ページのCSSが読み込まれる前にキャラ表示が始まっているのかも・・・

**Comment by kageori** [comment]
こちらではやはり再現しますね...

使用データは、最新kageori/add-materials（コミットのハッシュ値は656c45a3c62f50feee7b6861685a0306ebaf9c1f）内のpepa-s.jsonです。
<img width="531" alt="スクリーンショット 2022-09-11 15 00 17" src="https://user-images.githubusercontent.com/31335394/189528903-ff3274bb-0fde-4920-99ad-f38326f6153c.png">

**Comment by yugeta** [comment]
imageの表示サイズから大きさと座標を取得していた仕様を、登録データから計算で割り出す方式で安定サイズ表示できるようになりました。
これで遅い回線で、遅延読み込みしても、一定のサイズでの表示ができるようになります。
※ただし、ベースサイズ（出力予定サイズ）のcss読み込みが想定外の遅タイミングの場合、もしかしたら、サイズが安定しなくなるかもしれないので、その際は新たにissue立ち上げましょう！
