### ISSUE TITLE
アニメーションでポジションを変更すると、imgの追加モードでもポジションが変わってしまう

### ISSUE THREAD

**Issue by kageori** [yugeta/image-motion#6]
https://user-images.githubusercontent.com/31335394/182027379-6a7d33f6-c3a5-4e4a-bb03-251087d9c52e.mp4

**Comment by kageori** [comment]
新規アニメーションを追加した場合も、それまでの変形が引き継がれて表示されてしまう（値自体はクリアされているようなので、表示のみクリアされていない？）

**Comment by yugeta** [comment]
選択（active）されたオブジェクトが、最前面になるように、修正しました。
