### ISSUE TITLE
一旦画面を切り替えてAnimationモードに戻った時に数値が触れなくなっているとありがたい

### ISSUE THREAD

**Issue by kageori** [yugeta/image-motion#60]
①UploadやPlayなど他の画面に切り替えて、戻った時に、下図のように、アニメーションが空にもかかわらず、キーフレームを設定できるようになってしまうことがある。

<img width="1057" alt="スクリーンショット 2022-09-10 18 06 10" src="https://user-images.githubusercontent.com/31335394/189492050-290e19b7-c06e-486f-a3d3-5ece1ba13f2f.png">

②アニメーションが空の時には、常にこうなっていると、間違えないのでとてもありがたい。
<img width="1053" alt="スクリーンショット 2022-09-10 18 15 39" src="https://user-images.githubusercontent.com/31335394/189492215-9219cbc4-3bf2-4733-99af-94636155cdab.png">

### 再現条件
- 他の画面に行く直前、Animation画面で、「アニメーションをセットしていた（emptyではなかった）」かつ「パーツにフォーカスが当たっていた」 の2つの条件を満たす時、再びAnimation画面に戻った時に、emptyで数値が触れるようになっている。

**Comment by yugeta** [comment]
以下の内容を修正しました。
- animation-setting-list
- timeline
- property(shape , sound)
- shape-mode(points-view)
