### ISSUE TITLE
新規アニメーションをaddしても、以前別のアニメーションで設定したShapeがクリアされない

### ISSUE THREAD

**Issue by kageori** [yugeta/image-motion#63]

**Comment by kageori** [comment]
#64 と関連あり？

**Comment by kageori** [comment]
これは新しくaddしたアニメーションだが、図のように、Shapeキーを打たなくても、すでにShapeがついている（以前設定したShapeが初期値になっている？）。

<img width="662" alt="スクリーンショット 2022-09-13 23 49 03" src="https://user-images.githubusercontent.com/31335394/190015526-251a9b6c-4a86-46f4-90c2-b880f256fcc4.png">

**Comment by yugeta** [comment]
アニメaddの際にshapeのリセット処理ができてないですね。
対応します！

**Comment by yugeta** [comment]
修正しました。

【確認方法】
1. shapeアニメのついているanimation-nameに切り替える
2. animation-addで新規アニメーションを追加する。（この時点で見た目の画像はリセットされるが、ポイントがリセットされていなかった）
3. shape設定がされている画像を選択
4. ポイントが正常にリセットされている事を確認（jsエラーも無し）

【コーディング】
・次のモジュールを新たに追加 : shape/points_reset.js
・action/play.jsで、timeline毎に呼ばれる、transform_img_all関数の先でkeyframeデータが存在しないデータの度にリセットする仕様を追加。
