### ISSUE TITLE
Shapeリセットができない

### ISSUE THREAD

**Issue by kageori** [yugeta/image-motion#64]
キーフレーム追加してからリセット
-> 値が保存されない

https://user-images.githubusercontent.com/31335394/190015177-fcea7f35-5e88-448b-9288-dcb41c887113.mp4

リセットしてからキーフレーム追加する 
-> 想定外の動きをする

https://user-images.githubusercontent.com/31335394/190015185-50e93514-338b-4148-bb17-a79021d63e61.mp4

**Comment by yugeta** [comment]
ホントだ。リセットしたら、shapeポイントのメモリ値が壊れてるみたい。
コレ気が付かなかった！

**Comment by yugeta** [comment]
ポイントのソート処理が正常に動作していませんでした。
本件深いバグだったのに、見つけてくれてどうもありがとう！！
