### ISSUE TITLE
Scaleがついた状態でポジションを設定すると、アニメーション開始時に少しずれる

### ISSUE THREAD

**Issue by kageori** [yugeta/image-motion#65]
https://user-images.githubusercontent.com/31335394/190429289-b06dacae-2790-47fd-8150-4d7b706d8316.mp4

**Comment by yugeta** [comment]
これ、再現しないな〜、でもなんかガクガクしてるよね。
なんかゴミデータが１フレームに存在するように見えるな〜。
この該当jsonデータ見てみたいな〜

**Comment by kageori** [comment]
再現したりしなかったり、やはり微妙に謎な挙動でした。
問題が再現したNG.jsonと、再現しなかったOK.jsonと、rideを追加する前のoriginal.jsonを別途送付します。

### 作業手順
- stand,talk,walkのアニメーションを作った後（=original.json）で、bike.pngをアップロード
- standをコピーしてrideを作成
- stand,talk,walkで、bike.pngのopacityを0%の段階で0に設定。
- ここでbikeにposition-x,position-y, scale, opacity=1を追加

### 再現条件を完全に割り出せなかったので、怪しそうな部分メモ

- スクーターをどの子要素にも登録しないまま値を設定しようとしているからダメ？（添付図参照）
- opacityを設定すると、何かがおかしくなりそうな気配...？
- 作業をしながら、ポジションを設定するタイミングで、画面全体のスケールを変えると、NG.jsonになりそうな気配
- **playerモードで見ると、OK.jsonもやはりずれている**（動画参照）

<img width="704" alt="スクリーンショット 2022-09-16 1 18 22" src="https://user-images.githubusercontent.com/31335394/190525000-01593367-ff8c-4e3f-8ddf-0f333127cba8.png">

https://user-images.githubusercontent.com/31335394/190526439-41c848a5-0b1e-42a7-9369-36fcb129a8ed.mp4

**Comment by kageori** [comment]
bike.png
![bike](https://user-images.githubusercontent.com/31335394/190527116-9991832a-d339-4667-9fbf-9f4540cc7e0a.png)

**Comment by yugeta** [comment]
原因判明！
cssのtransform設定でscaleの記述位置が、場所毎に違っていたことが原因でした。
なので、座標移動してからscaleする場合はいいのだけど、
scaleしてから、座標移動すると、scaleした値の座標になるので、誤差が生じるため、scaleセットした時にガクっとなる表示になってました。
ということで、transformの値を一言で書き出すclassモジュールを作って、一元管理するようにしました。
（ただし、playerは別処理になるので、一元管理対象外になる。）
とりあえず、これでNGのデータも正常になっていると思います。
