### ISSUE TITLE
パーツの階層移動

### ISSUE THREAD

**Issue by kageori** [yugeta/image-motion#7]
パーツを上層に持っていきたい時に、階層がたくさんあると、上の方まで持っていけなくなる。

パーツを折りたたみできるか、上に動かせるようにできたら嬉しい。

https://user-images.githubusercontent.com/31335394/182028604-1257696d-9daa-4837-b191-4fafd0621b20.mp4

**Comment by yugeta** [comment]
移動時にスクロールするように機能追加しました。
