### ISSUE TITLE
playerで見た時、編集画面で正しく見えていたはずのパーツの再生が狂う

### ISSUE THREAD

**Issue by kageori** [yugeta/image-motion#82]
202206pepa-web/json/animation/pepa-s.jsonの、trapとliftでこのような現象が起こる（おそらく一番親のパーツに回転がついているから？）

https://user-images.githubusercontent.com/31335394/219979881-e4ea6d6e-6fb2-4f44-abda-c619bb6f5ede.mp4

**Comment by yugeta** [comment]
shapeとrotateの組み合わせで回転軸の座標に不具合があるみたいだね。
修正に向けて作業します！

**Comment by yugeta** [comment]
#083を修正して少し表示が変わりました。

<img width="528" alt="スクリーンショット 2023-02-28 21 34 13" src="https://user-images.githubusercontent.com/2545771/221855477-4779ea26-8992-4536-8c98-b1ea70d59f30.png">

一見前よりもバラバラに見えるかもしれないけど、左手と上半身だけが右下にずれている状態で、右手と足は正常な位置にあります。

これらの違いを調べてみたら、pos-zにマイナス値が入っているものは正常になっているようです。

何でそうなるかを現在調査中ですが、それが解明されたら、これも正常に表示できるはずです。

もう少しお待ちを・・・

**Comment by yugeta** [comment]
<img width="778" alt="スクリーンショット 2023-03-01 19 12 53" src="https://user-images.githubusercontent.com/2545771/222109702-3cd0a1a4-32fc-44e1-8e21-c59809883a80.png">

無事に、修正対応完了です！

**Comment by kageori** [comment]
ありがとうございます！！！たいへん助かりました。
Closeします！
