### ISSUE TITLE
playerと編集画面でshape挙動の差？

### ISSUE THREAD

**Issue by kageori** [yugeta/image-motion#83]
きのこの手の部分にshapeをつけているのだが、編集画面だと問題なく見えるが、playerの方で再生すると、手首から先がちぎれている。

https://user-images.githubusercontent.com/31335394/221386987-21c2df33-1e7c-4a80-94c5-0794f41a9bd8.mp4

**Comment by yugeta** [comment]
キノコの手がチョンパしている現象治りました。

原因は、やはり、rotate+shapeの時に発生する事象で、shape時にrotateする場合、本来の画像のサイズをはみ出す場合にギャップ値というのを取得しているんですが、その分をズラして回転を掛けていなかったのが原因です。

でも、#082のペパちゃんのイリュージョンは、さらに悪くなりました。（原因調査中です）

**Comment by kageori** [comment]
こちらもCloseします！ありがとうございました！
